services:
  backend:
    build: 
      context: ./backend-mdr
    container_name: painelfinanceiro_back
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: 
      context: .
    container_name: painelfinanceiro_front
    environment:
      # O navegador do usuário PRECISA desse link público para achar o Django
      - VITE_API_URL=https://api-painelfinanceiro.mdradvocacia.com/api
    depends_on:
      - backend
