services:
  backend:
    build: 
      context: ./backend-mdr
    container_name: painelfinanceiro_back
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: .
    container_name: painelfinanceiro_front
    environment:
      - VITE_API_URL=http://backend:8000/api
    ports:
      - "3005:80"
    depends_on:
      - backend
