"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'chave-de-fallback-apenas-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')

# Upload em massa da Base de Referência manda TODAS as linhas num POST só (JSON).
# O default do Django (2,5 MB) barra planilhas grandes com RequestDataTooBig depois
# que o nginx libera o corpo — sobe o teto pra 50 MB (par com client_max_body_size).
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB

CSRF_TRUSTED_ORIGINS = [
    f"https://{host}" for host in ALLOWED_HOSTS if host != '*'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'financeiro',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/app/data/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Arquivos enviados pelos usuários (contratos dos colaboradores).
# Vão para DENTRO da pasta de dados — que é o volume persistente do Coolify,
# o mesmo do SQLite. Fora dela, um redeploy apagaria os documentos.
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'data' / 'media'))
MEDIA_URL = '/media/'   # NÃO é servido direto: download passa por endpoint autenticado
# 25 MB por arquivo (o nginx já aceita 50 MB no POST)
DP_UPLOAD_MAX_BYTES = int(os.environ.get('DP_UPLOAD_MAX_BYTES', 25 * 1024 * 1024))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # DRF Token (emitido por /api/login/ e /api/sso/). TokenAuthentication
        # rejeita usuário inativo -> revogar acesso invalida o token na hora.
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # DEFAULT-DENY: toda a API exige usuário autenticado E ativo (liberado).
    # Os endpoints de login (/api/login/, /api/token/) e o /api/sso/ têm
    # permissão própria (AllowAny), então seguem abertos pra autenticar.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# --- SSO Microsoft Entra ID (via oauth2-proxy — mesmo approach do Flow/DOC) ---
# Quando SSO_ENABLED=True, GET /api/sso/ valida o cookie do oauth2-proxy
# server-side (chama SSO_VALIDATE_URL repassando o cookie .dunatecnologia.com,
# que o navegador manda same-origin), acha-ou-cria o User pelo e-mail e devolve
# um DRF Token (mesmo formato do /api/login/). Conta nova nasce PENDENTE
# (is_active=False) — acesso só após liberação do admin (painel é sensível).
# Senha continua valendo. Sem efeito enquanto SSO_ENABLED=False (default).
SSO_ENABLED = os.getenv('SSO_ENABLED', 'False') == 'True'
SSO_VALIDATE_URL = os.getenv('SSO_VALIDATE_URL', '')  # https://auth.dunatecnologia.com/oauth2/auth
SSO_AUTHORIZE_BASE = os.getenv('SSO_AUTHORIZE_BASE', 'https://auth.dunatecnologia.com')
SSO_EMAIL_HEADER = os.getenv('SSO_EMAIL_HEADER', 'X-Auth-Request-Email')

# E-mails que entram já LIBERADOS e como ADMIN (is_staff) no login SSO — os donos
# do painel. Separados por vírgula, SEM aspas no Coolify. Ex.:
# SSO_ADMIN_EMAILS=jonilsonvilela@mdradvocacia.com,ti@mdradvocacia.com
SSO_ADMIN_EMAILS = [
    e.strip().lower() for e in os.getenv('SSO_ADMIN_EMAILS', '').split(',') if e.strip()
]