# Generated by Django 5.0.3 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpdconfig',
            name='despesasBase',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpdconfig',
            name='headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpdconfig',
            name='pessoalApoio',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
