# Generated by Django 5.0.3 on 2026-07-28 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_ferias_na_folha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroFaturamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('faturamento', 'Centro de Faturamento'), ('infraestrutura', 'Centro de Infraestrutura')], default='faturamento', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ef_centros',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('grupo', models.CharField(choices=[('passivo', 'Contencioso Passivo'), ('credito', 'Recuperação de Crédito'), ('especializada', 'Especializada'), ('infra', 'Infraestrutura')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(blank=True, help_text='Centro de custo do DP de onde vem o custo real desta equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_estrutura', to='financeiro.dpcentrocusto')),
            ],
            options={
                'db_table': 'ef_equipes',
                'ordering': ['grupo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LinhaFaturamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('area', models.CharField(choices=[('passivo', 'Contencioso Passivo'), ('credito', 'Recuperação de Crédito'), ('especializada', 'Especializada')], max_length=20)),
                ('periodos', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='financeiro.centrofaturamento')),
                ('setor_legado', models.ForeignKey(blank=True, help_text='Setor do painel antigo que originou esta linha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_novas', to='financeiro.setor')),
            ],
            options={
                'db_table': 'ef_linhas',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('centro', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentual', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(blank=True, help_text='Alocação direta no centro (infraestrutura ou cliente sem linhas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='financeiro.centrofaturamento')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='financeiro.equipe')),
                ('linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='financeiro.linhafaturamento')),
            ],
            options={
                'db_table': 'ef_alocacoes',
            },
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(fields=('linha', 'equipe'), name='uq_alocacao_linha_equipe'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(fields=('centro', 'equipe'), name='uq_alocacao_centro_equipe'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('centro__isnull', True), ('linha__isnull', False)), models.Q(('centro__isnull', False), ('linha__isnull', True)), _connector='OR'), name='ck_alocacao_um_destino'),
        ),
    ]
