# Generated by Django 5.0.6 on 2026-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_faltas_calendario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faturamentodocumento',
            new_name='ef_faturame_linha_i_a9f074_idx',
            old_name='ef_fat_doc_linha_per_idx',
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='base_fgts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='base_inss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='inss_dif_ferias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='inss_ferias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='inss_salario',
            field=models.FloatField(default=0),
        ),
    ]
