# Generated by Django 5.0.6 on 2026-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_inss_decomposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpcolaborador',
            name='aprendiz',
            field=models.BooleanField(default=False, help_text='Contrato de aprendizagem: FGTS de 2% em vez de 8%'),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='fgts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='fgts_percent_aprendiz',
            field=models.FloatField(default=0.02),
        ),
    ]
