# Generated by Django 5.0.6 on 2026-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_aprendiz_e_fgts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_autonomo_usa_tabela_mensal',
            field=models.BooleanField(default=True, help_text='Autônomo/RPA usa a mesma tabela progressiva mensal.'),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_desconto_simplificado',
            field=models.FloatField(default=0, help_text='Desconto simplificado mensal em R$ (2025: 607,20). Zero desliga.'),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_faixas_13',
            field=models.JSONField(blank=True, default=list, help_text='Tabela do 13º (tributação exclusiva na fonte). Vazia usa a mensal.'),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_faixas_plr',
            field=models.JSONField(blank=True, default=list, help_text='Tabela ANUAL própria da PLR (Lei 10.101). Vazia = não tributa.'),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_isencao_maior_65',
            field=models.FloatField(default=0, help_text='Parcela isenta adicional para quem tem 65 anos ou mais, em R$.'),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_retencao_pj_dispensa',
            field=models.FloatField(default=0, help_text='Não retém de PJ quando o imposto apurado fica abaixo deste valor.'),
        ),
        migrations.AddField(
            model_name='dptabelafiscal',
            name='irrf_retencao_pj_percent',
            field=models.FloatField(default=0, help_text='Retenção sobre serviços de PJ (serviços profissionais: 1,5%).'),
        ),
    ]
