# Generated by Django 5.0.6 on 2026-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_irrf_estrutura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpfolhaitem',
            name='total_descontos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='total_proventos',
            field=models.FloatField(default=0),
        ),
    ]
