# Generated by Django 5.0.6 on 2026-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0029_totais_extrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpfolhaitem',
            name='adiantamento_ferias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='desconto_consignado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='outros_descontos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dplancamento',
            name='adiantamento_ferias',
            field=models.FloatField(default=0, help_text="Liquido do recibo de ferias, ja' pago adiantado. Desconta na folha do mes pra nao pagar duas vezes."),
        ),
        migrations.AddField(
            model_name='dplancamento',
            name='desconto_consignado',
            field=models.FloatField(default=0, help_text='Emprestimo consignado retido em folha e repassado ao banco.'),
        ),
        migrations.AddField(
            model_name='dplancamento',
            name='outros_descontos',
            field=models.FloatField(default=0, help_text='Outros descontos do mes.'),
        ),
        migrations.AddField(
            model_name='dplancamento',
            name='outros_descontos_desc',
            field=models.CharField(blank=True, default='', help_text="O que e' o 'outros descontos' — sem isto vira valor orfao que ninguem sabe explicar depois.", max_length=120),
        ),
    ]
