# Generated by Django 5.0.6 on 2026-08-14 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0030_descontos_nao_tributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpfolhaitem',
            name='liquido_em_conta',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DpConsignado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contrato', models.CharField(help_text='Número do contrato (aparece no extrato da contabilidade)', max_length=60)),
                ('banco', models.CharField(blank=True, default='', max_length=60)),
                ('parcela_valor', models.FloatField(help_text='Valor fixo descontado por mês')),
                ('parcelas_total', models.IntegerField(default=0, help_text='Quantidade de parcelas; 0 = sem prazo definido')),
                ('primeira_competencia', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignados', to='financeiro.dpcolaborador')),
            ],
            options={
                'db_table': 'dp_consignados',
                'ordering': ['-ativo', 'primeira_competencia'],
            },
        ),
    ]
