# Generated by Django 5.0.6 on 2026-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0031_consignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='dplancamento',
            name='adiantamento_ferias_auto',
            field=models.BooleanField(default=True, help_text='Calcula o adiantamento como o liquido do recibo de ferias. Desmarque para digitar um valor diferente.'),
        ),
    ]
