# Generated by Django 5.0.6 on 2026-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0032_adiantamento_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpfolhaitem',
            name='dsr_horas_extras',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='horas_extras_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='horas_extras_50',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpfolhaitem',
            name='valor_horas_extras',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dplancamento',
            name='horas_extras_100',
            field=models.FloatField(default=0, help_text='Horas extras em domingo/feriado (adicional de 100%).'),
        ),
        migrations.AddField(
            model_name='dplancamento',
            name='horas_extras_50',
            field=models.FloatField(default=0, help_text='Horas extras em dia util (adicional de 50%).'),
        ),
    ]
