# Generated by Django 5.0.6 on 2026-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0033_horas_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpfolhaitem',
            name='adiantamento_ferias_auto',
            field=models.BooleanField(default=True),
        ),
    ]
