# Generated by Django 5.0.6 on 2026-08-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0034_adiant_auto_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrofaturamento',
            name='setor_legado',
            field=models.ForeignKey(blank=True, help_text='Setor do painel legado que recebe o custo deste centro quando ele nao tem linha de faturamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_infra', to='financeiro.setor'),
        ),
    ]
